# Generated by Django 3.0.7 on 2020-06-06 10:46

from django.db import migrations, models
import rent.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rent_title', models.CharField(max_length=12)),
                ('speed', models.CharField(max_length=12)),
                ('brand', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=20)),
                ('bike_image', models.ImageField(upload_to=rent.models.image_upload_to_bike)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('text', models.CharField(max_length=12)),
            ],
        ),
    ]
