# Generated by Django 3.0.7 on 2020-06-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='brand_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='model',
            field=models.CharField(default='hi', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bike',
            name='speed_limit',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='model_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
