# Generated by Django 3.0.7 on 2020-06-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_auto_20200606_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
