# Generated by Django 3.0.7 on 2020-06-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_auto_20200606_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
