# Generated by Django 3.0.7 on 2020-06-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0007_auto_20200607_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='destinition_reverse',
            field=models.CharField(default='abc', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bike',
            name='destinition_straight',
            field=models.CharField(default='abc', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bike',
            name='price',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
