# Generated by Django 3.0.7 on 2020-06-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0008_auto_20200607_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinitionSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinition_straight', models.CharField(max_length=120)),
                ('destinition_reverse', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='bike',
            name='destinition_reverse',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='destinition_straight',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='price',
        ),
    ]
