# Generated by Django 3.0.7 on 2020-06-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0009_auto_20200607_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinitionselect',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
