# Generated by Django 3.0.7 on 2020-06-08 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rent', '0010_destinitionselect_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_point', models.CharField(max_length=120)),
                ('banner_image', models.ImageField(upload_to='')),
                ('banner_title', models.CharField(max_length=120)),
                ('banner_year_title', models.CharField(max_length=120)),
                ('banner_creative_title', models.CharField(max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
