# Generated by Django 3.0.7 on 2020-06-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0013_auto_20200608_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
    ]
