# Generated by Django 3.0.7 on 2020-06-08 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0015_auto_20200608_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dont_use', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.SelectPoint')),
            ],
        ),
    ]
