# Generated by Django 3.0.7 on 2020-06-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0017_finalrent'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalrent',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
