# Generated by Django 3.0.7 on 2020-06-08 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0019_auto_20200608_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalrent',
            name='bike_name',
        ),
        migrations.RemoveField(
            model_name='finalrent',
            name='email',
        ),
    ]
