# Generated by Django 3.0.7 on 2020-06-08 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0020_auto_20200609_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalrent',
            name='user',
        ),
    ]
