# Generated by Django 3.0.7 on 2020-06-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0025_auto_20200610_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalrent',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
