# Generated by Django 3.0.7 on 2020-06-05 16:49

import about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeoBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to=about.models.image_upload_to_banner)),
                ('banner_title', models.CharField(max_length=120)),
                ('banner_year_title', models.CharField(max_length=120)),
                ('banner_creative_title', models.CharField(max_length=120)),
                ('founder_image', models.ImageField(upload_to=about.models.image_upload_to_founder)),
                ('founder_name', models.CharField(max_length=120)),
                ('founder_title', models.CharField(max_length=120)),
                ('desciption_one', models.TextField()),
                ('desciption_two', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
    ]
