# Generated by Django 3.0.7 on 2020-06-05 17:21

import about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_image', models.ImageField(upload_to=about.models.image_upload_to_team)),
                ('person_name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('persom_number', models.CharField(max_length=120)),
                ('person_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
