# Generated by Django 3.0.7 on 2020-06-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20200605_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceobanner',
            name='extra_title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
