# Generated by Django 3.0.7 on 2020-06-04 15:26

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_title', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('button_title', models.CharField(max_length=120)),
                ('slider_image', models.ImageField(upload_to=home.models.image_upload_to_slider)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
