# Generated by Django 3.0.7 on 2020-06-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='slider_image',
        ),
        migrations.AddField(
            model_name='slider',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
