# Generated by Django 3.0.7 on 2020-06-05 15:50

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_name', models.CharField(max_length=120)),
                ('speaker_image', models.ImageField(upload_to=home.models.image_upload_to_speaker)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(upload_to=home.models.image_upload_to_main)),
            ],
        ),
    ]
